### ISSUE TITLE
u suck

### ISSUE THREAD

**Issue by jonahaberle** [illegalprime/uflix#1]
"docker: Error response from daemon: Conflict. The name "/uflix-main" is already in use by container 320b6595bbf349f501c7cec54dd833d127d0de4438a069701cdc94d9fa9b4157. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.
"

**Comment by illegalprime** [comment]
How did this bug happen?

**Comment by jonahaberle** [comment]
I don't remember

_Jonah Aberle_
_(615) 285-9814_
*Google+
http://t.sidekickopen55.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg7gbMJ8W7fclWK8rBpz6W8rByXx56dMmsf5FJzfl02?t=https%3A%2F%2Fplus.google.com%2F%2BJonahAberle%2F&si=6336732837707776&pi=eaf178d0-ba7c-41cb-bba2-52d83145ed5c
    *

**Comment by illegalprime** [comment]
K can't fix it then :cry:
