### ISSUE TITLE
¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by jonahaberle** [illegalprime/uflix#2]
Remove use of the official plex repo in your build file and replace it with a link to the latest deb file from plex.tv/downloads and add a flag to enable use of the "Plex Pass" version of plex for premium subscribers. 

Here is an example URL that points to the latest plex pass version for ubuntu 64bit

https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=E9WcevpzThpyCTU8v8ZM

Plex does a poor job of supporting their Ubuntu repo and recommends you download their app driect from their site. The current version on the repo you use is Version 1.1.3.2700. THe current version on the plex website for non-premium subscribers is 1.1.4.2757

Please help.

**Comment by illegalprime** [comment]
Cool, is this download link only for "Plex Pass" people or for everyone?
Also steps of the setup change for "Plex Pass" users?

**Comment by illegalprime** [comment]
I will add a flags to:
- [x] Manually provide a `.deb` package in the build script to use instead of upstream.
- [x] Clean all images and data before building again.

**Comment by jonahaberle** [comment]
Can you please also make sure the plex port (32400) is open by default to the docker box?

**Comment by jonahaberle** [comment]
I think you should just look over this dude's code and implement it somehow. Maybe have your build file ask for the email and password every time it runs.

https://github.com/mrworf/plexupdate
